#' Prepare dendrogram by transforming dendrogram segments.
#'
#' @keywords internal
#'
#' @param dendro_in Dendrogram object generated by
#' `some_matrix |> dist() |> hclust() |> as.dendrogram() |> dendextend::as.ggdend()`.
#' @param dend_dim Dimension the dendrogram will be plotted against (rows or columns).
#' @param dend_down Logical indicating if a dendrogram will be plotted along the bottom or top.
#' @param dend_left Logical indicating if a dendrogram will be plotted to the left or to the right.
#' @param dend_height Scaling parameter of dendrogram height.
#' @param full_plt Logical indicating if the whole heatmap is plotted or not.
#' @param cor_long Data frame containing the correlations that will be plotted in the heatmap.
#' @param annot_df Data frame containing annotations.
#' @param annot Logical indicating if annotations will be drawn for the specified dendrogram dimension.
#' @param annot_side Logical specifying which side the annotation will be drawn, analogous to 'dend_down' or 'dend_left'
#' (use the one in the same dimension as the dendrogram).
#' @param annot_pos Vector of the annotation positions along the opposite dimension.
#' @param annot_size Size of annotation cells, specified in heatmap cells (1 being the size of one cell).
#'
#' @return Data frame with dendrogram segment parameters.
#'
#' @examples
prepare_dendrogram <- function(dendro_in, dend_dim = c("rows", "cols"),
                               dend_down, dend_left, dend_height, full_plt, cor_long,
                               annot_df, annot, annot_side, annot_pos, annot_size) {

  dend_dim <- dend_dim[1]
  dend_seg <- dendro_in$segments

  # Rotate dendrogram to face heatmap
  rot_angle <- if (dend_dim == "rows") {
    # If row dendrogram rotate 90 or -90 degrees
    ifelse(dend_left, pi/2, -pi/2)
  } else {
    # Column dendrogram, no rotation or 180 degrees
    ifelse(!dend_down, 0, pi)
  }
  dend_seg[, c("x", "y")] <- as.data.frame(t(rotate(t(dend_seg[, c("x", "y")]), angle = rot_angle)))
  dend_seg[, c("xend", "yend")] <- as.data.frame(t(rotate(t(dend_seg[, c("xend", "yend")]), angle = rot_angle)))

  # If needed mirror the dendrogram around the middle if the rotation caused it to not line up with the correct rows
  if ((!dend_down & !dend_left) | (dend_down & dend_left & !full_plt) |
      (!dend_down & dend_left & full_plt)) {
    dend_seg <- mirror_dendrogram(dend_seg, dend_dim)
  }

  # Move dendrogram next to heatmap
  dend_seg <- move_dendrogram(dend_seg, cor_long, dend_dim,
                              ifelse(dend_dim == "rows", dend_left, dend_down),
                              annot_df, annot, annot_side, annot_pos, annot_size)

  # Rescale height of dendrogram
  if (dend_height != 1) {
    dend_seg <- scale_dendrogram(dend_seg, dend_dim,
                                 ifelse(dend_dim == "rows", dend_left, dend_down),
                                 dend_height)
  }

}
